### ISSUE TITLE
Invariant Violation: [2995,"RNSVGSvgView",{"width":"<<-Infinity>>"}] is not usable as a native method argument

### ISSUE THREAD

**Issue by vishal-bhil** [coinjar/react-native-wagmi-charts#101]
Getting above error on click of line chart in iOS(iPhone 13). (Android is working fine)

https://user-images.githubusercontent.com/34021048/183582822-a1387166-6261-4cc1-b92f-381010767e2e.mp4

**Comment by fariskhan563** [comment]
Facing the same issue since last week and can't really find anything to fix it on IOS :(

**Comment by fariskhan563** [comment]
Also while trying to interact with candle stick chart it is giving a different error on IOS

`ExceptionsManager.js:149 Invariant Violation: [37515,"RCTView",{"opacity":1,"transform":[{"translateX":"<<NaN>>"}]}] is not usable as a native method argument`

**Comment by fariskhan563** [comment]
> Getting above error on click of line chart in iOS(iPhone 13). (Android is working fine)
> 
>  Simulator.Screen.Recording.-.iPhone.13.-.2022-08-09.at.12.17.42.mp4

Seems like I was able to fins the cause of the above mentioned errors.
It is happening due to **Debug with chrome** being enabled on the device.

Disable debugger and it will work just fine. @vishal-bhil
