### ISSUE TITLE
[Feature request] Ability to specify `minDurationMs` for LineChartCursor gesture handler

### ISSUE THREAD

**Issue by Gordeev1** [coinjar/react-native-wagmi-charts#117]
Thank you for the amazing library. 

It would be quite useful to be able to override gesture handler config of `LineChartCursor` from `LineChart.CursorLine`

```jsx
<LineChart.CursorLine
    {/* So chart doesn't conflict with navigation back gesture and scroll views  */}
    minDurationMs={300}
/>
```

**Comment by nandorojo** [comment]
This is already implemented.

**Comment by nandorojo** [comment]
Ah I see they forgot to forward the props onto `LineChartCursor`.

**Comment by nandorojo** [comment]
If you use `LineChart.Cursor` directly, you're able to do this. So you might want to use that and add your own line by forking their line for now.

**Comment by nandorojo** [comment]
My PR at #120 would fix this.

**Comment by nandorojo** [comment]
@daginfinity can you?

**Comment by julian-dotcom** [comment]
How do you delay the scrolling for a few seconds? I couldn't get it to work by using minDurationMs
