### ISSUE TITLE
Aways show PriceText and DatetimeText at the current most recent data point when cursor not selected

### ISSUE THREAD

**Issue by colinfran** [coinjar/react-native-wagmi-charts#125]
Is there a way to always show `PriceText` and `DatetimeText` at the current most recent data point when `CursorCrosshair` is not being touched?

In the below gif screenshot of my project, I would like the `PriceText` and `DatetimeText` at the bottom to always show text. 
I am looking to make it so that I can drag the `CursorCrosshair` but once I let go, it defaults to going back to showing the most recent datapoint (the last datapoint in the array) resulting in `PriceText` and `DatetimeText` defaulting back to display the most recent datapoint's price and time.

![phone](https://user-images.githubusercontent.com/16205865/226521753-ae274739-989d-40e8-87c6-bde490bb6127.gif)

**Comment by colinfran** [comment]
I currently have a hacky way but I feel like there should be a better way. This is what I do currently, but theres definitely a a delay.

I use `onActivated` and `onEnd` to change the `showCurrentPrice` state.
When activated, `showCurrentPrice` is false, meaning it shows the animated text price, and when `showCurrentPrice` is true, it shows the default current value text price.

I just feel like theres a better way than this.

<img width="577" alt="Screen Shot 2023-03-20 at 10 16 25 PM" src="https://user-images.githubusercontent.com/16205865/226524484-6d8c8496-79b3-489e-919c-5c152e394976.png">

**Comment by JamesIde** [comment]
Hi @colinfran, how did you deal with your onCurrentIndexChange? I am struggling greatly trying to pass the index to update either in state or context to be used by other components, but it is triggering a re-render every time we update inside the callback. Tried memoizing the component and functions where possible.

**Comment by colinfran** [comment]
@JamesIde so i think you need to make sure that you are not setting your state/context as a dependency to the 

```
const onCurrentIndexChange = useCallback((index: number) => {
    
  }, [])
```

**Comment by JamesIde** [comment]
@colinfran thanks - I understand. I actually solved my re-rendering problem by moving from Context to Zustand to avoid re-rendering for all context consumers...
