### ISSUE TITLE
Ability to control precision of textlabels

### ISSUE THREAD

**Issue by ArkyBald** [coinjar/react-native-wagmi-charts#127]
Would be nice to have the ability to control the precision of textlabels, similar to how the price display works. Thanks

**Comment by arancauchi** [comment]
Hi @ArkyBald by text labels do you mean for example `LineChart.Tooltip` or `LineChart.PriceText`? If so, the formatting of those can be controlled using the `format` worklet function.

**Comment by michaelpomogajko** [comment]
Would like to piggy bag on this. In my use case I only work with whole numbers.
Would be nice to be able to set formatting on the tooltip directly, or also have the prop 'variant' to display the value as is, and not having the double float digit.

**Comment by michaelpomogajko** [comment]
@arancauchi resurfacing this issue. 
There is no apparent way to format a tooltips text. The `format` worklet only works with PirceText, not with the tooltip.
Any ideas?

**Comment by JuanRdBO** [comment]
Hey I have the same issue. I'd love to be able to control the precision on the labels. If you have very tiny numbers it looks bad:
![image](https://github.com/coinjar/react-native-wagmi-charts/assets/28183468/89653193-a5bf-436e-9276-316ee2e63d4b)

**Comment by JuanRdBO** [comment]
The format function actually does work with the tooltip:

![Screenshot 2024-01-12 at 16 28 22](https://github.com/coinjar/react-native-wagmi-charts/assets/28183468/7219e4b4-609e-4558-a975-4b4a15c1c2c5)

**Comment by michaelpomogajko** [comment]
@JuanRdBO thanks for the tip, but unfortunately getting the following error when trying to do it with 

```ts
textProps={{
  format: ({ formatted }) => {
    return Number(formatted).toFixed(0);
   },
}}
```

![Simulator Screenshot - iPhone 15 Pro - 2024-01-13 at 00 57 07](https://github.com/coinjar/react-native-wagmi-charts/assets/8081364/b1bc03bd-aff8-4dac-9a9e-cbc48892e20e)

**Comment by michaelpomogajko** [comment]
@JuanRdBO actually you're right, adding the worklet directive solves it

```ts
textProps={{
  format: ({ value }) => {
   'worklet';
   return Number(value).toFixed(0);
  },
}}
```
