### ISSUE TITLE
How To Add Vertical Data and Horizontal Data on the Side and below Of The Chart.

### ISSUE THREAD

**Issue by mksmanish** [coinjar/react-native-wagmi-charts#131]

**Comment by arancauchi** [comment]
Hi @mksmanish i'm not really sure what you question means sorry. Do you mean x and y axis labels?

**Comment by dragonfi-kent** [comment]
> Hi @mksmanish i'm not really sure what you question means sorry. Do you mean x and y axis labels?

Yes, X and Y labels. any way to achieve those?

**Comment by honeybadger26** [comment]
Marking this as a duplicate of https://github.com/coinjar/react-native-wagmi-charts/issues/154
