### ISSUE TITLE
[QUESTION] No format prop for LineChart.Tooltip

### ISSUE THREAD

**Issue by shivansal** [coinjar/react-native-wagmi-charts#132]
Hi. I am trying to customize the value shown when pressing down on a point in the graph. In specific, I want to add a dollar sign in front of the value to indicate a currency value. Please let me know if anyone has been able to accomplish this or if I am looking at the wrong prop object. Thank you.

**Comment by arancauchi** [comment]
Hey @shivansal yes that's indeed possible to change the formatting on the cursor tooltip. You can do so as follows:

```
  const format = ({ value }) => {
    'worklet'
    return `$${value}`
  };

	return (
		...
	        <LineChart.Tooltip textProps={{ format }}  />
		...
	);
```

**Comment by shivansal** [comment]
Ah okay. thank you
