### ISSUE TITLE
How to use chart hooks?

### ISSUE THREAD

**Issue by yilunc** [coinjar/react-native-wagmi-charts#14]
There is a note under the Hooks documentation that states:

```
The following hooks are only accessible inside the LineChart.Provider or CandlestickChart.Provider.
```

I am trying to implement the `LineChart.useChart` hook so that I can display the current chart status in a text component instead of the provided tooltip text.

Chart provider:

```
        <LineChart.Provider data={monthSteps}>
          <Box height={200} background={"#FFF"}>
            <LineChart width={width} height={200}>
              <LineChart.Path />
              {
                // @ts-ignore
                <LineChart.CursorCrosshair
                  onActivated={() => {
                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                  }}
                  onEnded={() => {
                    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                  }}
                />
              }
            </LineChart>
          </Box>
          {renderChartText()}
        </LineChart.Provider>
```

In `renderChartText` I attempt to get the chart data using a hook like so:

```
const renderChartText = () => {
    const { currentX, currentY, currentIndex, data, domain, isActive } =
      LineChart.useChart();
}
```

The above does not work so I assume I'm using Hooks wrong. Apologise if this is a newbie question but I'm definitely not a React pro yet. Was hoping to get tips on how to implement these hooks? Thanks in advance, and thank you for making such a beautiful and easy to use library! 🙏

**Comment by yilunc** [comment]
Also as a side note, I had to add a `ts-ignore` on `LineChart.CursorCrosshair` because the component requires children even though it doesn't look like that's the case in the documentation?

**Comment by nandorojo** [comment]
You should make new components altogether. This components should call the hooks, and return the other internal chart components. React lets you make custom components that return other ones that way.

You might not want to use React state, and instead use reanimated shared values for better performance. And you can then set display to flex or none (or better yet, animate the opacity) inside of useAnimatedStyle. This will allow you to trigger no re-renders.

**Comment by joey-harward** [comment]
@nandorojo is there any way to show an example of this? I really appreciate your help.
