### ISSUE TITLE
x scale proportional to time.

### ISSUE THREAD

**Issue by RenatoSerra22** [coinjar/react-native-wagmi-charts#140]
Hellow,

Is there any way to make the distance between two points respect the scale of time between them? Right now points are evenly split across the x axis in the graph

**Comment by cam-shaw** [comment]
@RenatoSerra22 On line chart yes this is possible by setting the `xDomain` prop on the LineChart.Provider.
For the xDomain value, provide an array with 2 numbers, the lowest timestamp and highest timestamp in your data.

Let's say I had this data
```
const dataToShow = [
  { timestamp: 1661904060, value: 1 },
  { timestamp: 1661925060, value: 1.3 },
  { timestamp: 1661926260, value: 2 },
];

```
and we put it into our provider...
```
<LineChart.Provider
// other props
data={dataToShow}
 xDomain={[dataToShow[0], dataToShow[dataToShow.length -1]}>
// rest of code
</LineChart.Provider>
```

It will give you the desired result.

**Comment by RenatoSerra22** [comment]
beautifuuuuuuul thanks so much @cam-shaw !

**Comment by rodrigof1307** [comment]
I was about to post this exact same question. This prop of the provider should be on the Component APIs section of the docs

**Comment by cam-shaw** [comment]
> I was about to post this exact same question. This prop of the provider should be on the Component APIs section of the docs

You're 100% correct, and this is my bad. When I added the feature in a PR I forgot to update the docs with it. I'll take a look during the week at adding some documentation.

**Comment by RenatoSerra22** [comment]
@cam-shaw the gradient doesnt seem to respect the domain tho

<img width="340" alt="Screenshot 2023-07-04 at 13 18 56" src="https://github.com/coinjar/react-native-wagmi-charts/assets/12633730/4586284b-71d5-4675-a308-d11bf4beb4af">

**Comment by cam-shaw** [comment]
Iiinteresting... Had a look and I think I know how to solve the gradient issue.. Looks fairly simple to resolve, the gradient just needs to also respect the xDomain if provided. 
No promises yet but give me some time and I'll try this week to have a play and I'll get something up for the maintainers to review.

**Comment by ChaseK30** [comment]
Nevermind I figured it out, the timestamps were formatted differently then the data that was being shown, I did find a weird reaction when putting the xdomain, the dot seems to be hanging off the screen 
![Simulator Screen Shot - Iphone 14 pro 16 2 - 2023-07-05 at 15 18 54](https://github.com/coinjar/react-native-wagmi-charts/assets/98040043/2db9bdba-9885-4023-b576-5a01f5cc65e1)

**Comment by cam-shaw** [comment]
@ChaseK30 If you're able to, would be great if you can give this PR a test. I have fixed up the x position for the dot - would be great to know if it resolves your issues.

https://github.com/coinjar/react-native-wagmi-charts/pull/144

Let me know if you have any issues integrating it into your project. 

1. Clone the PR
2. Change package.json of PR version to `2.3.0-local.0` to avoid any package conflicts
3. `yarn build && yarn pack` - This will output a path to the terminal similar to `success Wrote tarball to "/Users/.../react-native-wagmi-charts-v2.3.0-local.0.tgz`
4. In your personal project, run `yarn install pathToTarball`

**Comment by ChaseK30** [comment]
checking now!

**Comment by ChaseK30** [comment]
@cam-shaw there are no build commands

**Comment by cam-shaw** [comment]
apologies... `yarn pack` instead of `yarn build`. Have edited my above comment for anyone else looking.

**Comment by cam-shaw** [comment]
@ChaseK30 sorry, `yarn prepare` instead of `yarn build`. Have updated my comment above.

**Comment by ChaseK30** [comment]
Sorry for the delay running into a ton of dependency issues

**Comment by cam-shaw** [comment]
@ChaseK30 no worries at all. Could be good to document on the PR if the dependency issues are specific to the PR. I'd imagine the maintainers could throw that into the release notes.

**Comment by ChaseK30** [comment]
![Screenshot 2023-07-05 at 6 22 17 PM](https://github.com/coinjar/react-native-wagmi-charts/assets/98040043/10e833ce-b9d4-44a0-9247-d05706521e34)

Gettin a ton of these errors trying to run it at all

**Comment by cam-shaw** [comment]
@ChaseK30 those are unfortunately/fortunately (depending on how you look at it 😅 ) unrelated to the PR. 
Double check your @react/types and react native types are correct for the React version you're using.

Perhaps even go as far as deleting the `node_modules` directory and installing dependencies again. Bit hard to debug from here unfortunately.

Were you already on react-native-wagmi-charts 2.3.0?

**Comment by ChaseK30** [comment]
in my personal project yes, but i am getting all these errors running a `yarn install && yarn prepare && yarn pack` before getting it into my personal project

**Comment by RenatoSerra22** [comment]
just saw the PR thank you @cam-shaw for being so quick with it!

**Comment by RenatoSerra22** [comment]
Found another issue :D when dragging over the line, the labels dont show the correct timestamp/value

**Comment by cam-shaw** [comment]
@RenatoSerra22 are you able to provide some sample data for me to test with? I believe I have fixed this in the PR as well.

**Comment by TobiasGrothmann** [comment]
Hi there,
I still ran into the issue of tooltips disregarding the xDomain which was adressed in https://github.com/coinjar/react-native-wagmi-charts/pull/144

using "react-native-wagmi-charts": "2.6.0",

----

Some screenshots to illustrate:

without xdomain (works great):
<img width="83" alt="Screenshot 2024-12-12 at 10 53 26" src="https://github.com/user-attachments/assets/dcd4529a-ef68-4f6a-afb0-657465850120" />

with xdomain (tooltip values are offset)
<img width="87" alt="Screenshot 2024-12-12 at 11 11 03" src="https://github.com/user-attachments/assets/a103e3fd-3946-4846-b0c8-8a525186c308" />
<img width="74" alt="Screenshot 2024-12-12 at 10 53 16" src="https://github.com/user-attachments/assets/79ac6b8e-e3ba-4a5d-913a-e36cc2dfa370" />

**Comment by cam-shaw** [comment]
@TobiasGrothmann please correct me if I'm wrong.
The tooltip shows the value of the wrong data point that is currently selected?

**Comment by TobiasGrothmann** [comment]
@cam-shaw 
Exactly. The tooltip shows the value another data point than is selected.
It seems to me like it uses the value of the data point that would be correct if no xDomain was set.
