### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNGestureHandlerButton, js engine: hermes

### ISSUE THREAD

**Issue by ziziele** [coinjar/react-native-wagmi-charts#142]
I have an Expo React Native app, and I'm facing two different errors based on whether I have `react-native-gesture-handler` installed or not.

Without `react-native-gesture-handler` installed:
When I don't include the react-native-gesture-handler package (expo install react-native-gesture-handler), I encounter the following error during Android bundling:
```js
Android Bundling failed 6873ms
Unable to resolve module react-native-gesture-handler from C:\...\pricetracker\node_modules\react-native-wagmi-charts\src\charts\candle\Crosshair.tsx: react-native-gesture-handler could not be found within the project or in these directories:
  node_modules
   6 |   LongPressGestureHandlerEventPayload,
   7 |   LongPressGestureHandlerProps,
>  8 | } from 'react-native-gesture-handler';
     |         ^
   9 | import Animated, {
  10 |   useAnimatedGestureHandler,
  11 |   useSharedValue,
› Reloading apps
Android Bundling complete 2701ms
Android Running app on sdk_gphone_x86_64
```
With `react-native-gesture-handler` installed:
When I do include the react-native-gesture-handler package (expo install react-native-gesture-handler), I encounter the following error related to an "Invariant Violation":
```js
Invariant Violation: Tried to register two views with the same name RNGestureHandlerButton, js engine: hermes
```
I'm unsure how to proceed with resolving these issues. Any guidance or suggestions would be greatly appreciated.

**Comment by barrymichaeldoyle** [comment]
How did you resolve it?
