### ISSUE TITLE
Question: Dynamically display price on top of chart when user click on chart. Revert to current price when user unpresses.

### ISSUE THREAD

**Issue by julian-dotcom** [coinjar/react-native-wagmi-charts#145]
I want to use the `const price = LineChart.usePrice();` to have a dynamic price display on top of the chart. Once a user touches the chart, the price display should be adjusted to the price the user is currently hovering over. Once the user unpresses, it should go back to the original price. How do I do this?

<img width="321" alt="Screenshot 2023-07-05 at 17 13 29" src="https://github.com/coinjar/react-native-wagmi-charts/assets/74622908/c85d8aad-7275-4d56-b5dc-b6923e434a44">

I've been able to console.log the updated value with `useAnimatedReaction`, but I haven't been able to successful display the price change.

**Comment by julian-dotcom** [comment]
Figured it out. 

Since it's usePrice returns an animated / shared value, you cannot use a normal Text component. 

Instead, you need to create a shared value with the useDerivedValue hook from reanimated. 

This, you then need to visualize using the AnimatedText component also exported from wagmi charts.

**Comment by cihangir-mercan** [comment]
hello? can you share the code please? @julian-dotcom

**Comment by honeybadger26** [comment]
Hi @cihangir-mercan.

One way to do this is to use `LineChart.PriceText` and `formatPrice` which are both exported by the library. Here I am printing the currently selected price on the chart. If no price is selected then the price from the last data point is used:

```jsx
import { View } from 'react-native';
import { LineChart, formatPrice } from 'react-native-wagmi-charts';

// ... inside your component:

const formatValue = ({ value }) => {
  'worklet';
  const valToPrint = value
    ? value
    : data[data.length - 1].value.toFixed(2);

  return formatPrice({ value: valToPrint.toString() });
};

<LineChart.Provider data={data}>
  <View style={{ position: 'relative' }}>
    <LineChart.PriceText
      style={{ position: 'absolute', top: 10, left: 10 }}
      format={formatValue}
    />
    <LineChart>
      <LineChart.Path color="black" />
      <LineChart.CursorCrosshair />
    </LineChart>
  </View>
</LineChart.Provider>

```

https://github.com/coinjar/react-native-wagmi-charts/assets/27768821/28fdd084-a33f-454c-ab85-fe68f152cc01

Hope this helps.

**Comment by cihangir-mercan** [comment]
> Hi @cihangir-mercan.
> 
> One way to do this is to use `LineChart.PriceText` and `formatPrice` which are both exported by the library. Here I am printing the currently selected price on the chart. If no price is selected then the price from the last data point is used:
> 
> ```js
> import { View } from 'react-native';
> import { LineChart, formatPrice } from 'react-native-wagmi-charts';
> 
> // ... inside your component:
> 
> const formatValue = ({ value }) => {
>   'worklet';
>   const valToPrint = value
>     ? value
>     : data[data.length - 1].value.toFixed(2);
> 
>   return formatPrice({ value: valToPrint.toString() });
> };
> 
> <LineChart.Provider data={data}>
>   <View style={{ position: 'relative' }}>
>     <LineChart.PriceText
>       style={{ position: 'absolute', top: 10, left: 10 }}
>       format={formatValue}
>     />
>     <LineChart>
>       <LineChart.Path color="black" />
>       <LineChart.CursorCrosshair />
>     </LineChart>
>   </View>
> </LineChart.Provider>
> ```
> 
>  Screen.Recording.2024-05-07.at.17.09.05.mov 
> Hope this helps.

yeah. nice one. i have found out this too. thanks.
