### ISSUE TITLE
Is there a way to get clicks on crosshairs in a candlestick chart?

### ISSUE THREAD

**Issue by jihoon8730** [coinjar/react-native-wagmi-charts#150]
![image](https://github.com/coinjar/react-native-wagmi-charts/assets/88140865/e9d361fc-0265-46d8-962e-59738515d200)
true if the crosshair is touched, false if not, etc.

**Comment by honeybadger26** [comment]
Hi @jihoon8730

Do you mean detecting if the crosshair is active? That can be done by using the `CandlestickChart.useChart` hook and checking that `currentX` and `currentY` are not equal to `-1`
```
import { runOnJS, useDerivedValue } from 'react-native-reanimated';
import { CandlestickChart } from 'react-native-wagmi-charts';

const PositionText = () => {
  const { currentX, currentY } = CandlestickChart.useChart(); // These are Reanimated shared values
  const [crosshairActive, setCrosshairActive] = React.useState(false);

  useDerivedValue(() => {
    runOnJS(setCrosshairActive)(currentX.value !== -1 && currentY.value !== -1);
  });

  return <Text>Crosshair active: {crosshairActive ? 'Yes' : 'No'}</Text>;
};
```

**Comment by jihoon8730** [comment]
@honeybadger26 

This is an old post, but
but using a different chart solved it!
Thank you so much for your answer

I'll pin it in case it helps anyone else
