### ISSUE TITLE
Crosshair snapToPoint crashing

### ISSUE THREAD

**Issue by Rayne182** [coinjar/react-native-wagmi-charts#153]
I am using Expo v48.0.7 and wagmi-charts v2.3.0 and I am trying to implement the following:

       
```
<LineChart.CursorCrosshair 
    snapToPoint // I have tried: ={true} , ="true" , ={"true"}
    color={COLORS.primary}
>
       <LineChart.Tooltip />
</LineChart.CursorCrosshair>
```

And the error I get:
"Uncaught error - undefined is not a function. linearScalePositionAndIndex (..\line\Cursor.tsx)"

**Comment by cam-shaw** [comment]
@Rayne182 There is a [known crash](https://github.com/coinjar/react-native-wagmi-charts/pull/148) due to an incorrect version of d3-array in the project.
Add this to your package.json file, run `yarn install` and let me know if it resolves the issue.

```json
"resolutions": {
  "d3-array": "3.1.6",
}
```

**Comment by Rayne182** [comment]
This solved it for me, thank you so much!
