### ISSUE TITLE
Programmatically display CursorLine

### ISSUE THREAD

**Issue by tiste** [coinjar/react-native-wagmi-charts#167]
Hello,

I have a use case where some buttons aim to go forward/backward over time.

It would be great if there is a way to move/display the cursorline from code (like hook).

Thanks again for the lib.

**Comment by honeybadger26** [comment]
Hi @tiste.

Great suggestion! How about an `at` property that can be used like:
```
<LineChart.CursorLine at={indexToDrawLine} />
```

**Comment by tiste** [comment]
Hey @honeybadger26, it's done :) #183
