### ISSUE TITLE
When will a new release come out for the npm package?

### ISSUE THREAD

**Issue by ChaseK30** [coinjar/react-native-wagmi-charts#168]
I know a lot of updates were pushed to main from @cam-shaw , When can we expect a release to be pushed?  It would be great to have this changes available in the package

**Comment by cam-shaw** [comment]
@ChaseK30 Not sure if this helps you.. but I'm considering moving away from this package. Tried to bring some stuff up to date but it appears the project isn't having the support from CoinJar that it needs to continue.

**Comment by ChaseK30** [comment]
@cam-shaw Please let me know if you do, your changes have very much helped in the ways I am using this package.  If you do end up branching out onto your own I will be following

**Comment by arancauchi** [comment]
Hi @cam-shaw and @ChaseK30, apologies for the lack of movement on this library. @honeybadger26 will be dedicating some time to maintaining this project going forward.

**Comment by AlekseyP18** [comment]
@arancauchi Hi, all who uses this package will be really appreciate if you release new version with all of those fixes

**Comment by honeybadger26** [comment]
Hi all. Thanks for your patience. A new release has been pushed out: https://www.npmjs.com/package/react-native-wagmi-charts. Check it out!
