### ISSUE TITLE
Issues when data changes

### ISSUE THREAD

**Issue by nandorojo** [coinjar/react-native-wagmi-charts#2]
Looks like there's an issue when changing the data passed to a chart. I tried to make a reproduction on [Expo Snack](https://snack.expo.dev/@nandorojo/aa90cf), but it seems like this lib doesn't work with it (I can ask the Expo team about this, Reanimated 2 libs usually need extra config for Snack.)

Here's a video:

https://user-images.githubusercontent.com/13172299/136065100-f5410c10-e075-4bb5-966a-bf82ed335c9c.mov

Issues:

1. The updated data doesn't fill the entire width of the chart.
2. There is an `undefined is not an object` issue sometimes.

My best guess is that 2 things are causing it:

1. Number of data points is changing, so it's looking for an index that may not exist, or something like that.
2. The max/min x values are changing, since it's getting data that starts further back.

Thanks again for a great lib!

**Comment by nandorojo** [comment]
It seems like the issue is here:

<img width="452" alt="Screen Shot 2021-10-05 at 12 38 35 PM" src="https://user-images.githubusercontent.com/13172299/136065688-0f91ac9a-4732-426c-beb3-a78dc78e63f3.png">

My guess is that `mixPath` is expecting the same number of items to interpolate.

**Comment by nandorojo** [comment]
Here is a full reproduction.

<details>
<summary>Click me to see code</summary>

Here we update the data every 5 seconds.

```tsx
import { LineChart as Chart } from 'react-native-wagmi-charts'
import React, { useEffect, useState } from 'react'

const data = [
  {
    timestamp: 1625945400000,
    value: 33575.25,
  },
  {
    timestamp: 1625946300000,
    value: 33545.25,
  },
  {
    timestamp: 1625947200000,
    value: 33510.25,
  },
  {
    timestamp: 1625948100000,
    value: 33215.25,
  },
]

const data2 = [...data, ...data]

export function LineChart() {
  const [line, setLine] = useState(data)

  useEffect(() => {
    setInterval(() => {
      setLine((line) => {
        return line === data ? data2 : data
      })
    }, 5000)
  }, [])

  return (
    <Chart.Provider data={line}>
      <Chart>
        <Chart.Path />
        <Chart.CursorCrosshair />
        <Chart.CursorLine />
      </Chart>
    </Chart.Provider>
  )
}
```
</details>

If we change this line:

```ts
const data2 = [...data, ...data]
```

To this:

```ts
const data2 = [...data].reverse()
```

Then it works fine. Which means, the graph currently breaks if the number of items along the path changes.

**Comment by jxom** [comment]
Yep, you are right. Seems like `mixPath` doesn't like paths of different lengths. I have merged and published a fix for this on `1.0.4`, but I am not quite happy with the animations for it right now. I'll need some time to revisit this.

**Comment by nandorojo** [comment]
Sounds good, thanks!

**Comment by jxom** [comment]
Can you try `1.0.5`? I just integrated `d3-interpolate-path`, and it is working much better now!

![Kapture 2021-10-07 at 10 50 13](https://user-images.githubusercontent.com/7336481/136298909-5306ef46-52d3-4a9d-9c6c-ecd1f224f046.gif)

**Comment by jxom** [comment]
Hmm interesting... Yeah, a reproduction would be great.
