### ISSUE TITLE
Multiple paths

### ISSUE THREAD

**Issue by nandorojo** [coinjar/react-native-wagmi-charts#29]
It would be cool to show multiple paths on a line chart:

![image](https://user-images.githubusercontent.com/13172299/139954162-f3f8f452-c8c8-40bf-a46d-3d5f8a78e7a5.png)

I think this *should* work, but the problem is that the data is a singleton on the provider. Maybe I should just absolute position another provider beneath the first one? Would be cool to have a first-class solution for this.

**Comment by jxom** [comment]
Sounds like a valid use case! Could have a some kind of dictionary passed to `data`, and the relevant paths reference a key? e.g.

```tsx
const data = {
  foo: [{ timestamp: ..., value: ... }],
  bar: [{ timestamp: ..., value: ... }]
}

<LineChart.Provider data={data}>
  <LineChart key="foo">
    <LineChart.Path />
    <LineChart.CursorCrosshair />
  <LineChart>
  <LineChart key="bar">
    <LineChart.Path />
    <LineChart.CursorCrosshair />
  <LineChart>
</LineChart.Provider>
```

**Comment by nandorojo** [comment]
Yeah I had the same thing in mind. Though we might have to use an `id` prop or something rather than `key` (can a component access its own `key`?)

**Comment by jxom** [comment]
Yeah, `id` sounds better.

**Comment by nandorojo** [comment]
I'm trying to wrap my head around how to do this.

1. The root level provider uses `data` to construct the domain and range. This should be okay: it can merge the values and find the biggest/smallest if someone passes a dictionary.
2. The `contextValue` has `data` in it, presumably to be consumed by lower-level components. We could split this one out into a `DataContext`, and override it in `LineChart` if `(props.id != null)`. And then have a `useData` hook to access this `data`.
  a. I actually think this makes sense either way. The `data` context doesn't necessarily have to be coupled to the shared values.

<img width="823" alt="Screen Shot 2021-11-02 at 7 26 13 PM" src="https://user-images.githubusercontent.com/13172299/139965494-4e3d1dd5-db3d-4102-87f1-0e1a45ce4dc4.png">

**Comment by nandorojo** [comment]
I have something in the works, going to test it out. Will make a PR if it works as expected.

**Comment by nandorojo** [comment]
Okay so I got this working quite well: https://www.loom.com/share/6dd897e0a47c438ead300481df652780

The one remaining issue is the fact that the `currentY` value is scoped to the root provider. This value should probably get calculated on the fly, using `data` and `currentX`, rather than inside of the gesture handler for `LineChartCursor`.

This is what `Cursor.tsx` looks like:

```tsx
const onGestureEvent = useAnimatedGestureHandler<
    GestureEvent<LongPressGestureHandlerEventPayload>
  >({
    onActive: ({ x }) => {
      if (parsedPath) {
        const boundedX = x <= width ? x : width;
        isActive.value = true;
        currentX.value = boundedX;
        currentY.value = getYForX(parsedPath, boundedX) || 0;

        // on Web, we could drag the cursor to be negative, breaking it
        // so we clamp the index at 0 to fix it
        // https://github.com/coinjar/react-native-wagmi-charts/issues/24
        const minIndex = 0;
        const boundedIndex = Math.max(
          minIndex,
          Math.round(boundedX / width / (1 / (data.length - 1)))
        );

        currentIndex.value = boundedIndex;
      }
    },
    onEnd: () => {
      isActive.value = false;
      currentIndex.value = -1;
    },
  });
```

Here, the `currentY` is getting set, rather than read. So I think the final thing I have to do is make this calculate on the fly with `useDerivedValue`, and then we're good.

**Comment by nandorojo** [comment]
https://user-images.githubusercontent.com/13172299/140000543-385f3240-56fd-41c6-bc56-1059b51f6e9b.mp4

Alright, I think it's good to go now. Sending a PR for testing etc.
