### ISSUE TITLE
CandlestickChart Crosshair doesnot work on android

### ISSUE THREAD

**Issue by harensarma** [coinjar/react-native-wagmi-charts#36]

**Comment by jxom** [comment]
Hi.

Can you please add a description to this. Preferably example code & steps to reproduce.

**Comment by BubbleTrouble14** [comment]
Can't seem to get the CursorCrosshairs to work at all. I am running the example project but the cursors don't appear on longpress.

**Comment by BubbleTrouble14** [comment]
https://github.com/BubbleTrouble14/GraphReanimated2. Here i create a repo which might help reproducing the issue. Might be something to do with depency verisions.

**Comment by BubbleTrouble14** [comment]
It somehow doesnt fire the touch event at all, not allowing any cursor to appear.

**Comment by jxom** [comment]
Can you update to 1.8.0 and try again please?

**Comment by BubbleTrouble14** [comment]
Will do thank you.

**Comment by BubbleTrouble14** [comment]
https://gyazo.com/26ef009a69b7429b4d11621fcde9788e. Still no cursor showing sadly.

**Comment by BubbleTrouble14** [comment]
Okay, i tried running the app with the metro bundler and then it worked. So the issue is when using react native cli to run android apps.

**Comment by harensarma** [comment]
no still not working after updating to 1.8.0. works fine on iOS, not on an android device (also emulator)

https://user-images.githubusercontent.com/24252804/141988116-e1eecf80-9684-4c5a-941c-6aabde63bc92.mov

**Comment by harensarma** [comment]
> Can you update to 1.8.0 and try again please?

no still not working after updating to 1.8.0. works fine on iOS, not on an android device (also emulator)

https://user-images.githubusercontent.com/24252804/141988331-b186ff78-f7b5-4fa7-a727-a7ddbe1ae2d2.mov

**Comment by jxom** [comment]
Can you please provide me with a code example?

**Comment by harensarma** [comment]
> Can you please provide me with a code example?

This is implementation:
`<CandlestickChart.Provider data={this.state.chart_data}>
                  <CandlestickChart height={300}>
                    <CandlestickChart.Candles positiveColor="#5ed100" negativeColor="#ff0000" />
                    <CandlestickChart.Crosshair>
                      <CandlestickChart.Tooltip />
                    </CandlestickChart.Crosshair>
                  </CandlestickChart>
                </CandlestickChart.Provider>`

and this is import:

`import { CandlestickChart } from 'react-native-wagmi-charts';`

Rest, it is working fine at iOS devices.
