### ISSUE TITLE
Add docs for Hermes

### ISSUE THREAD

**Issue by nandorojo** [coinjar/react-native-wagmi-charts#39]
`DateTimeText` has some issues formatting with Hermes, since Hermes doesn't have Intl support. The later versions do for Android (I think RN 0.66 +), and on iOS it like pseudo works (doesn't do full formatting, it's still a WIP). So I think there needs to be a basic polyfill for that.

For context, `react-native-paper-dates` has this in their docs for hermes: https://github.com/web-ridge/react-native-paper-dates#below-react-native-066

Expo SDK 43 also supports Hermes, so it's become mainstream enough to mention I think.

**Comment by honeybadger26** [comment]
Hi @nandorojo. The RN version recently was upgraded to 0.72.8. I'm wondering if you're still having this issue?
