### ISSUE TITLE
[Question] Add Text next to the graph as a Y value

### ISSUE THREAD

**Issue by fpmirabile** [coinjar/react-native-wagmi-charts#44]
Hi everyone, 

I'm having issues doing this, I want to display different texts based on the Y position of the axis, without having to "Touch" or using the crosshair in order to show the values we pretend to use.
Is this possible?

Thanks

**Comment by jxom** [comment]
There is no in-built way to display labels based on a path position right now. Would be nice though.

**Comment by nandorojo** [comment]
Could reuse the tooltip logic pretty easily for this. Would be really useful for placing min/max values on the chart

**Comment by nandorojo** [comment]
![image](https://user-images.githubusercontent.com/13172299/143607849-dcc00cac-9a21-40b1-aaa8-99e32ffaa61c.jpeg)

Here's a good example from coinbase. 

@jxom I could pick this up if you give me a little guidance on the API. Maybe we give it an `at` value? Would be nice to just pass the at to the tooltip that exists to not have to reimplement the positioning logic.

**Comment by hannojg** [comment]
I added support for labels / static tooltips in this PR: https://github.com/coinjar/react-native-wagmi-charts/pull/81
Looking forward to discussing this one (I just picked an API lol)
