### ISSUE TITLE
Highlight path sections

### ISSUE THREAD

**Issue by nandorojo** [coinjar/react-native-wagmi-charts#46]
![image](https://user-images.githubusercontent.com/13172299/142033337-aec118e7-6c39-4f83-886e-23430ce13ec0.png)

It would be nice to highlight ranges along a path. Notice that the start of the path is faded out. This example is from Robinhood.

```tsx
const highlighted = [
  [0, 2],
  [12, 14]
]

<LineChart.Path highlighted={highlighted} highlightWhile="active" />
```

**Comment by jxom** [comment]
So I actually have this on a branch right now, however, haven't had a chance to finish it yet! 

https://github.com/coinjar/react-native-wagmi-charts/blob/partial-paths/example/src/LineChart.tsx#L26

I think I like the terminology "highlight" better than "color" though. So maybe `LineChart.Highlight` is a better API.

**Comment by honeybadger26** [comment]
Hi @nandorojo. Are you happy for this to be marked as closed as it was added in https://github.com/coinjar/react-native-wagmi-charts/pull/52?
