### ISSUE TITLE
crosshair not working at android (device & simulator)

### ISSUE THREAD

**Issue by harensarma** [coinjar/react-native-wagmi-charts#54]
Crosshair Not working at android only, working at iOS.

This is implementation: 

`<CandlestickChart.Provider data={this.state.chart_data}>
                  <CandlestickChart height={300}>
                    <CandlestickChart.Candles positiveColor="#5ed100" negativeColor="#ff0000" />
                    <CandlestickChart.Crosshair>
                      <CandlestickChart.Tooltip />
                    </CandlestickChart.Crosshair>
                  </CandlestickChart>
                </CandlestickChart.Provider>`

Watch the video, please.

https://user-images.githubusercontent.com/24252804/143674943-827a2a58-8aff-4a20-ab4c-ed3bb5abc9f0.mp4

**Comment by lsorin81** [comment]
make sure your MainActivity has this method:
```
 @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
```

**Comment by harensarma** [comment]
NO, I have not put. After putting, it is working fine. Thank you. Can you please add this in the documentation. This will help the beginers like me.
