### ISSUE TITLE
LineChart Cursors not working on Android

### ISSUE THREAD

**Issue by dmytro19** [coinjar/react-native-wagmi-charts#59]
First of all, thanks for amazing library. On iOS, this is very looks great and working well as expected.
But when I trying to on `Android(device, emulator)` I can't see `LineChart.CursorLine` and `LineChart.CursorCrosshair` of `LineChart`. It seem to the gesture(touch) is not working on Chart. 

**[Replicated example video](https://d.pr/v/00etK0)**

Do you have any solution? Please help me to solve this problem. Thank you in advance.

### Environment
My project have created by `create-react-native-app` with typescript not `expo`.

```
"react-native": "0.66.2",
"react-native-gesture-handler": "^1.10.3",
"react-native-haptic-feedback": "^1.13.0",
"react-native-wagmi-charts": "2.0.0", 
```

**Comment by andra961** [comment]
I probably got your back man, try wrapping the chart in `GestureHandlerRootView` imported from `react-native-gesture-handler`, it worked for me. I know it can be subtle, but it's written in `react-native-gesture-handler` documentation: [https://docs.swmansion.com/react-native-gesture-handler/docs/#installation](url)

**Comment by dmytro19** [comment]
@andra961 Great work! Thank you It's works for now. 😎

**Comment by ZaidQ797** [comment]
> I probably got your back man, try wrapping the chart in `GestureHandlerRootView` imported from `react-native-gesture-handler`, it worked for me. I know it can be subtle, but it's written in `react-native-gesture-handler` documentation: [https://docs.swmansion.com/react-native-gesture-handler/docs/#installation](url)

I've wrapped  my Chart Module with GestureHandlerRootView but still not able to drag the cursor and even cursor not showing

**Comment by dmytro19** [comment]
@ZaidQ797 Can you share your code how to wrap `GestureHandlerRooView` ?
