### ISSUE TITLE
LineChart.CursorCrosshair Working Fine on IOS but in Android it's Not Working

### ISSUE THREAD

**Issue by princerajkolkata** [coinjar/react-native-wagmi-charts#67]
![image](https://user-images.githubusercontent.com/7336481/133027332-009b8996-4141-4865-bfd6-777e63b5e44d.gif)

Here I am posting The code of App.js. Here on IOS when I am clicking the chart it shows the LineChart.Tooltip values perfectly , but in android when I click nothing happens but the chart shows perfectly. May be I have missed something as I am new in react native
an Help will really be appreciated

`import * as React from 'react';
import Animated, { useSharedValue, useAnimatedStyle, withSpring } from 'react-native-reanimated';
import {
  SafeAreaView,
  View,
  Button
} from 'react-native';
import 'react-native-gesture-handler';
import { LineChart } from 'react-native-wagmi-charts';

const data = [
  {
    "timestamp": 1626945400000,
    "value": 33575.25
  },
  {
    "timestamp": 1626946300000,
    "value": 33545.25
  },
  {
    "timestamp": 1626947200000,
    "value": 33510.15
  },
  {
    "timestamp": 1626948100000,
    "value": 33215.61
  },
  {
    "timestamp": 1626949000000,
    "value": 33445.23
  },
  {
    "timestamp": 1626949900000,
    "value": 33435.51
  },
  {
    "timestamp": 1626950800000,
    "value": 33480.66
  },
  {
    "timestamp": 1626951700000,
    "value": 33440.25
  },
  {
    "timestamp": 1626952600000,
    "value": 33485.23
  },
  {
    "timestamp": 1626953500000,
    "value": 33515.21
  },
  {
    "timestamp": 1626954400000,
    "value": 33570.77
  },
  {
    "timestamp": 1626955300000,
    "value": 33640.45
  },
  {
    "timestamp": 1626956200000,
    "value": 33645.34
  },
  {
    "timestamp": 1626957100000,
    "value": 33670.33
  },
  {
    "timestamp": 1626958000000,
    "value": 33740.25
  },
  {
    "timestamp": 1626958900000,
    "value": 33770.25
  },
  {
    "timestamp": 1626959800000,
    "value": 33705.25
  },
  {
    "timestamp": 1626960700000,
    "value": 33760.25
  },
  {
    "timestamp": 1626961600000,
    "value": 33670.25
  },
  {
    "timestamp": 1626962500000,
    "value": 33870.25
  }
];

export default function App() {
  const offset = useSharedValue(0);

  const animatedStyles = useAnimatedStyle(() => {
    return {
      transform: [{ translateY: offset.value * 255 }],
    };
  });

  return (
      <LineChart.Provider data={data}>
        <LineChart>
          <LineChart.Path />
          <LineChart.CursorCrosshair
          >
            <LineChart.Tooltip position="top" 
              style={{
                backgroundColor: 'red',
                borderRadius: 4,
                color: 'white',
                fontSize: 18,
                padding: 4,
              }}
            />
            <LineChart.Tooltip position="bottom">
              <LineChart.DatetimeText />
            </LineChart.Tooltip>
          </LineChart.CursorCrosshair>
        </LineChart>
      </LineChart.Provider>

  );
};`

**Comment by NinnjA254** [comment]
I have the exact same problem

**Comment by lxc-xx** [comment]
My workaround:
https://github.com/coinjar/react-native-wagmi-charts/issues/73#issuecomment-1055333633

**Comment by vivekperumal** [comment]
Here is how I fixed the issue. 

Go to android folder/src/main/Java/MainActivity.java file.

Import below on top:
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

Add this following line in createReactActivityDelegate method:

`@Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegateWrapper(this,
      new ReactActivityDelegate(this, getMainComponentName())
       //Add these lines to make crosshair work in android.
      **{
          @Override
          protected ReactRootView createRootView() {
              return new RNGestureHandlerEnabledRootView(MainActivity.this);
          }
      }**
    );
  }`
