### ISSUE TITLE
Touching chart doesn't work in android but does on iOS

### ISSUE THREAD

**Issue by glenskie16** [coinjar/react-native-wagmi-charts#73]
Touching the chart on an android machine doesn't 'interact' but iOS is perfect. Is there anything extra I need to put on my page to make this work on android ? 

Here is my code. Thank you!

```<LineChart.Provider data={points}>
              <LineChart height={SIZE / 3.5} width={SIZE - 48}>
                <LineChart.Path color='rgba(194, 24, 91, 1)'/>
                <LineChart.CursorCrosshair color='white'/>
              </LineChart>
              <LineChart.PriceText format={({ value }) => {'worklet';const formattedPrice = formatUSD(value);return `${formattedPrice}`;}} precision={9} style={[tw("font-bold"),{color: 'white', margin: 4}]}/>
              <LineChart.DatetimeText style={[tw("font-bold"),{color: 'white', margin: 4}]}/>
            </LineChart.Provider>```

**Comment by lxc-xx** [comment]
I am having the same issue.

**Comment by lxc-xx** [comment]
i have the same issue.

**Comment by lxc-xx** [comment]
Well, to those who have the same issue, here is my walk around.

Wrap your component using a HOC (gestureHandlerRootHOC) from React Native Gesture Handler
`const ExampleWithHoc = gestureHandlerRootHOC(() => (
    <View>
      <DraggableBox />
    </View>
  );
);

export default function Example() {
  return (
    <Modal>
      <ExampleWithHoc />
    </Modal>
  );
}`


Reference: https://docs.swmansion.com/react-native-gesture-handler/docs/#android

**Comment by glenskie16** [comment]
Hmm, interesting. ill try this out! If i cant get this to work i might have to move on to another charting system. Even though I like this one alot

**Comment by glenskie16** [comment]
This solved my issue! Thanks!

**Comment by vivekperumal** [comment]
Here is how I fixed the issue.

Go to android folder/src/main/Java/MainActivity.java file.

Import below on top:
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

Add this following line in createReactActivityDelegate method:

@Override protected ReactActivityDelegate createReactActivityDelegate() { return new ReactActivityDelegateWrapper(this, new ReactActivityDelegate(this, getMainComponentName()) //Add these lines to make crosshair work in android. **{ @Override protected ReactRootView createRootView() { return new RNGestureHandlerEnabledRootView(MainActivity.this); } }** ); }

**Comment by SimonDamberg** [comment]
@vivekperumal The code to replace is not in my MainActivity.java, and placing the new code there throws the errors below. Which versions are you running?

```/Users/simondamberg/Documents/Qognica/mobile-qapsel/android/app/src/main/java/com/qognicafinance/qapsel/MainActivity.java:21: error: cannot find symbol
  @Override protected ReactActivityDelegate createReactActivityDelegate() { return new ReactActivityDelegateWrapper(this, new ReactActivityDelegate(this, getMainComponentName()) { @Override protected ReactRootView createRootView() { return new RNGestureHandlerEnabledRootView(MainActivity.this); } } ); }
                      ^
  symbol:   class ReactActivityDelegate
  location: class MainActivity
/Users/simondamberg/Documents/Qognica/mobile-qapsel/android/app/src/main/java/com/qognicafinance/qapsel/MainActivity.java:21: error: cannot find symbol
  @Override protected ReactActivityDelegate createReactActivityDelegate() { return new ReactActivityDelegateWrapper(this, new ReactActivityDelegate(this, getMainComponentName()) { @Override protected ReactRootView createRootView() { return new RNGestureHandlerEnabledRootView(MainActivity.this); } } ); }
                                                                                       ^
  symbol:   class ReactActivityDelegateWrapper
  location: class MainActivity
/Users/simondamberg/Documents/Qognica/mobile-qapsel/android/app/src/main/java/com/qognicafinance/qapsel/MainActivity.java:21: error: cannot find symbol
  @Override protected ReactActivityDelegate createReactActivityDelegate() { return new ReactActivityDelegateWrapper(this, new ReactActivityDelegate(this, getMainComponentName()) { @Override protected ReactRootView createRootView() { return new RNGestureHandlerEnabledRootView(MainActivity.this); } } ); }
                                                                                                                              ^
  symbol:   class ReactActivityDelegate
  location: class MainActivity
/Users/simondamberg/Documents/Qognica/mobile-qapsel/android/app/src/main/java/com/qognicafinance/qapsel/MainActivity.java:21: error: cannot find symbol
  @Override protected ReactActivityDelegate createReactActivityDelegate() { return new ReactActivityDelegateWrapper(this, new ReactActivityDelegate(this, getMainComponentName()) { @Override protected ReactRootView createRootView() { return new RNGestureHandlerEnabledRootView(MainActivity.this); } } ); }
                                                                                                                                                                                                        ^
  symbol: class ReactRootView
/Users/simondamberg/Documents/Qognica/mobile-qapsel/android/app/src/main/java/com/qognicafinance/qapsel/MainActivity.java:21: error: method does not override or implement a method from a supertype
  @Override protected ReactActivityDelegate createReactActivityDelegate() { return new ReactActivityDelegateWrapper(this, new ReactActivityDelegate(this, getMainComponentName()) { @Override protected ReactRootView createRootView() { return new RNGestureHandlerEnabledRootView(MainActivity.this); } } ); }

Note: /Users/simondamberg/Documents/Qognica/mobile-qapsel/android/app/src/main/java/com/qognicafinance/qapsel/MainActivity.java uses or overrides a deprecated API.
```

**Comment by cyberkaidev** [comment]
> Well, to those who have the same issue, here is my workaround.
> 
> Wrap your component using a HOC (gestureHandlerRootHOC) from React Native Gesture Handler
> 
> But this still leaves issue on android. The touching stops after a few seconds on android.
> 
> ```
> import {gestureHandlerRootHOC} from "react-native-gesture-handler";
> 
> const ExampleWithHoc = gestureHandlerRootHOC(() => (
>     <View>
>       <DraggableBox />
>     </View>
>   );
> );
> 
> export default function Example() {
>   return (
>     <Modal>
>       <ExampleWithHoc />
>     </Modal>
>   );
> }
> ```
> 
> Reference: https://docs.swmansion.com/react-native-gesture-handler/docs/#android

Thank you

**Comment by TheAhmadSami** [comment]
I found another solution, just wrap your chart component with `<GestureHandlerRootView>`

`import {GestureHandlerRootView} from 'react-native-gesture-handler';`

`<GestureHandlerRootView>
   <HistoricalCharts data={data} />
</GestureHandlerRootView>`
