### ISSUE TITLE
Gestures do not work with Expo SDK 44

### ISSUE THREAD

**Issue by jaibheeman** [coinjar/react-native-wagmi-charts#76]
The cursor gestures do not work with Expo SDK 44 (latest).

Fix: Taken from Expo 44 docs
"react-native-gesture-handler now requires a GestureHandlerRootView wrapper. As of v2, you now need to wrap your app with a <GestureHandlerRootView> component, as described [in the related installation documentation](https://docs.swmansion.com/react-native-gesture-handler/docs/#js)."

**Comment by aerielcruz** [comment]
This example helped
https://github.com/coinjar/react-native-wagmi-charts/issues/73#issuecomment-1055333633
