### ISSUE TITLE
It's possible to move cursor off the chart in on the left side

### ISSUE THREAD

**Issue by sallar** [coinjar/react-native-wagmi-charts#77]
Hi, 

When scrubbing on the chart using the cursor, it's possible to scrub off the chart. 

https://user-images.githubusercontent.com/768052/155680288-1ba18928-957f-475f-adc8-ea363dd900d6.mp4

**Comment by sallar** [comment]
Temporarily released under `@sallar/react-native-wagmi-charts` until this PR is merged.

**Comment by cam-shaw** [comment]
Patch-package of the PR if anyone else has this problem
https://gist.github.com/cam-shaw/ac800e8abfdff13f2e5617e4bdf5fedc

Good work @sallar
