### ISSUE TITLE
How to display high price and low price on chart at high and low pick of chart

### ISSUE THREAD

**Issue by priyanshop** [coinjar/react-native-wagmi-charts#91]

**Comment by ylubinets** [comment]
Hello @priyanshop 

`const pricesArr = historyPrices?.map(item => {
    return item.value;
  });

  const max = Math.max(...pricesArr);
  const min = Math.min(...pricesArr);

  const axisLabel = (isMax: boolean) => {
    return (
      <Text style={styles.axis}>
        {currency}
        {isMax ? cryptoPriceModified(max) : cryptoPriceModified(min)}
      </Text>
    );
  };`

**Comment by arancauchi** [comment]
Hi @priyanshop, you can see an example of this [here](https://github.com/coinjar/react-native-wagmi-charts/blob/767ab380271b18fbb44ef8969bc68031d65e589f/example/src/LineChart.tsx#LL67C16-L67C16)
