### ISSUE TITLE
Suspicious memory leak

### ISSUE THREAD

**Issue by yigithanyucedag** [coinjar/react-native-wagmi-charts#95]
I use LineChart and CandlestickChart components in same screen. When I navigate to the screen, ram usage is spiking and never drop down when the screen component is unmounted. 

Here is the codes of screen that I use the charts inside of it.

[https://gist.github.com/yigithanyucedag/86f33acd1c788f2300e512dc08e8d585](https://gist.github.com/yigithanyucedag/86f33acd1c788f2300e512dc08e8d585)

Dependencies:
"react": "18.0.0",
"react-native": "0.69.0",
"react-native-wagmi-charts": "^2.1.0",
"react-native-reanimated": "^2.8.0",

**Comment by nandorojo** [comment]
gist doesn't work fyi
